### ISSUE TITLE
Anim Component doesn't show template overrides

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/editor#678] opened 2022-02-01 16:45 UTC
When using the Anim Component in a template instance, I can't apply changes to the Anim Component to the template.

Differences are visible in the overrides panel at the top (but there is no way to apply them individually, only "apply all".

The Anim Component interface doesn't show overrides to the template.

**Comment by yaustar** [comment] 2022-02-01 16:52
Confirmed in a new project

https://playcanvas.com/project/877189/overview/anim-component-template-bug

https://user-images.githubusercontent.com/16639049/152013175-bafb90b2-db92-464a-ac92-331817c33057.mp4

**Comment by yaustar** [comment] 2022-02-01 18:13
@daredevildave Just to check, are you saying 'apply all' works? And also, are there specific anim component values that can't be applied individually or is it any of the properties?

**Comment by daredevildave** [comment] 2022-02-01 22:23
Exactly. In my case I had changes to the Anim Component and changes to the Script Component, but I couldn't apply on the Anim Component changes. The Script Component had a blue highlight and I could right-click to apply the changes. The Anim Component did not.

I mentioned that in case I had missed some UI in the design which let me use the template interface at the top of the sidebar (as pictured above) to apply changes component by component. I could only see a button to apply all changes.

**Comment by willeastcott** [comment] 2022-02-01 22:28
Looks like a fix was just merged for this by @zachpeterpaul. We'll aim to deploy within a day or so.

**Comment by yaustar** [comment] 2022-02-01 23:14
@daredevildave Sorry, just want to make sure that I'm looking at the right issue: no matter what parameter/attribute was changed on the anim component, you couldn't apply individually.  Or was it a specific one that didn't show up in the diff?

**Comment by daredevildave** [comment] 2022-02-01 23:20
No changes to the anim component show up as diffs either in the component interface or in the template "view diffs" interface in the sidebar.

I do see the "total" number of differences in the template interface at the top of the side bar.

**Comment by daredevildave** [comment] 2022-02-01 23:22
<img width="689" alt="Screenshot 2022-02-01 at 3 21 18 PM" src="https://user-images.githubusercontent.com/504980/152068050-f9ca77d1-d012-4324-a51d-9d99f782f48b.png">

<img width="321" alt="Screenshot 2022-02-01 at 3 22 07 PM" src="https://user-images.githubusercontent.com/504980/152068088-121a2844-c1f3-42d4-8cd3-94d23f367265.png">

**Comment by yaustar** [comment] 2022-02-01 23:45
That's really weird. If the issue is still there, can you make a fork of the project please and add 'yaustar' to the team and I take a look tomorrow?

**Closed** 2022-02-10 16:35 UTC
Labels: bug, area: templates, area: animation
