### ISSUE TITLE
Uploaded FBX > container is not rendering.

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/editor#456] opened 2021-07-12 11:20 UTC
When uploading FBX, with Impot Hierarchy enabled, does not render model.
Refreshing the editor - fixes an issue.

### Steps to Reproduce

1. Create new project
2. Switch Asset Tasks > Import Hierarchy on
3. Upload FBX
4. Drag template to scene

### Issue: 
Render component is not rendering, inspector is not showing model as well in top preview.
There are exceptions in console log: `Uncaught TypeError: Cannot read property 'format' of null`

**Comment by yaustar** [comment] 2021-07-12 12:27
Does refreshing the tab help?

**Comment by flyingbaba** [comment] 2021-07-12 17:03
Yep, refresh helps!

**Comment by mvaligursky** [comment] 2021-09-08 14:59
This is most likely fixed now, I cannot reproduce it anymore. Please reopen with repro steps if you still get this. Closing.

**Closed by mvaligursky** 2021-09-08 14:59 UTC
Labels: bug, area: asset import, area: viewport
