### ISSUE TITLE
Changing script order doesn't work

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#975] opened 2023-02-20 11:12 UTC
Changing script order on editor doesn't work. It was working before, for some reason it doesn't save anymore.

Video : https://streamable.com/nv8fhu

**Comment by willeastcott** [comment] 2023-02-20 11:20
@ellthompson is on the case. AFAIK, this should be resolved today. Thanks for reporting.

**Comment by willeastcott** [comment] 2023-02-20 11:22
Closing since it's a dupe of https://github.com/playcanvas/editor/issues/972

**Closed by willeastcott** 2023-02-20 11:22 UTC
Labels: bug, area: ui
