### ISSUE TITLE
Add Search Branch feature to version control

### ISSUE THREAD

**Issue by ki11roy** [playcanvas/editor#535] opened 2021-09-07 15:50 UTC
It is rather hard to find a branch if there are many. It would be nice to have a context search in the branch selector.
![image](https://user-images.githubusercontent.com/1812070/132374334-97d9ffca-eed1-4b7e-b224-e6ae0a14a181.png)

**Comment by yaustar** [comment] 2021-09-07 16:31
Closed as duplicate of https://github.com/playcanvas/editor/issues/306

**Closed by yaustar** 2021-09-07 16:31 UTC
