### ISSUE TITLE
link values fot width-height and/or scale

### ISSUE THREAD

**Issue by FranciscoBozzo** [playcanvas/editor#514] opened 2021-08-25 02:22 UTC
It would be nice to have a "linked values" (or "proportional transform") checkbox for width and height properties in Element and Collision components. Also would be handy for scale property.

The way it would work is if the checkbox is "checked" and any value is changed, all other values get changed in the same proportion, so that the object gets modified proportionally in every axis.

Cheers!

**Comment by yaustar** [comment] 2021-08-25 06:59
Duplicate of https://github.com/playcanvas/editor/issues/289

**Closed by yaustar** 2021-08-25 06:59 UTC
