### ISSUE TITLE
Project wide setting to choose which font is default selected when creating new text elements

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#554] opened 2021-09-21 10:17 UTC
There is behaviour where newly created text elements will choose a font asset if there's one present in the project.

However, if there are multiple, there is no way for the developer to choose a specific one.

**Comment by willeastcott** [comment] 2024-11-10 23:31
Duplicate of https://github.com/playcanvas/editor/issues/460. Closing.

**Closed by willeastcott** 2024-11-10 23:31 UTC
Labels: area: ui, feature request
