### ISSUE TITLE
GLB asset download from context menu

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1090] opened 2024-01-30 10:49 UTC
The GLB assets are missing a download option from the context menu (available only in inspector panel).

![image](https://github.com/playcanvas/editor/assets/5677782/59343567-4d7e-4c44-bdc6-4e915ae43e1f)

**Comment by willeastcott** [comment] 2024-11-10 14:20
Duplicate of https://github.com/playcanvas/editor/issues/248. Closing.

**Closed by willeastcott** 2024-11-10 14:20 UTC
Labels: bug
