### ISSUE TITLE
It is possible to import an FBX where root bone is not set on certain render components

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/editor#732] opened 2022-04-04 11:24 UTC
Try importing this FBX:

[mario-tpose.zip](https://github.com/playcanvas/editor/files/8409195/mario-tpose.zip)
.
You'll notice that only two of the eight render components have the root bone correctly set. To fix this, the developer needs to go through each render component and manually hook up the root bone.

**Comment by yaustar** [comment] 2022-04-04 16:31
Duplicate of https://github.com/playcanvas/editor/issues/602

**Comment by mvaligursky** [comment] 2022-04-04 16:37
> Duplicate of #602

It's not a duplicate at all, and those are very independent issues.

**Comment by yaustar** [comment] 2022-04-04 18:42
Oops, got it confused the issue found here where the Root Node wasn't added to render components https://forum.playcanvas.com/t/issue-adding-asset-to-model-component-from-fbx-import-from-mixamo/24315/17

Thought I had a ticket for this 🤔

**Comment by mvaligursky** [comment] 2022-04-21 13:33
this has been fixed by @slimbuck and is waiting for a release.

**Comment by yaustar** [comment] 2022-04-27 11:14
Released in https://github.com/playcanvas/editor/releases/tag/v1.21.42

**Closed by yaustar** 2022-04-27 11:14 UTC
Labels: bug, area: asset import, blitz candidate
