### ISSUE TITLE
Wordwrap functionality for code editor

### ISSUE THREAD

**Issue by devcem** [playcanvas/editor#926] opened 2022-11-14 11:16 UTC
This is a feature request, is it possible to have word wrapping functionality for the code editor?

<img width="326" alt="Screen Shot 2022-11-14 at 12 06 57" src="https://user-images.githubusercontent.com/7432641/201646433-26113724-f415-455a-8bc1-25f4598b7ada.png">

<img width="256" alt="Screen Shot 2022-11-14 at 12 07 35" src="https://user-images.githubusercontent.com/7432641/201646612-fc31abc1-01ec-4da0-abef-e033c48b186f.png">

**Comment by yaustar** [comment] 2022-11-14 11:16
Duplicate of https://github.com/playcanvas/editor/issues/923

**Closed by yaustar** 2022-11-14 11:16 UTC
Labels: duplicate, area: code editor, feature request
