### ISSUE TITLE
Custom color palette

### ISSUE THREAD

**Issue by bjornsyse** [playcanvas/editor#1192] opened 2024-08-30 09:00 UTC
Hi, small feature request

It would be helpful to include a small color palette where one could save some reoccuring colors used through a project. Avoid having a txt file with hex codes opened while developing.

Somehere in this color chooser perhaps. Could be as simple as showing a swatch for the 5 or 10 most recently used color codes, or color codes present in the project currently. 

![image](https://github.com/user-attachments/assets/dc263047-b275-4c90-88bf-bc29c5d9bfba)

Regards
Björn

**Comment by willeastcott** [comment] 2024-11-09 22:22
This is actually a duplicate of an issue you logged a long time ago on the PCUI repo:

https://github.com/playcanvas/pcui/issues/305

I'm sorry it still hasn't been addressed. But I'll close this in favor of the original one for now.

**Closed by willeastcott** 2024-11-09 22:22 UTC
Labels: feature request
