### ISSUE TITLE
Project is down

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/editor#255] opened 2020-12-14 21:37 UTC
### Description

My project seem to be down. Maybe due to some update from you regarding (only-usage of .glb animations, which I don't like either ... both options [glb and json]) should be available - and with a please :-)

It is so broke, that the background turns black at export, no matter what.
(at normal editor launch it works, both both types of publish crashes - turns black)

* URL to a simple, reproducible test case that illustrates the problem clearly
https://playcanvas.com/editor/scene/1054601 (launch is ok)
+ https://playcanv.as/b/SnHV73c7/ (turns black)
* Screenshots
![image](https://user-images.githubusercontent.com/6838800/102138323-7376a200-3e5c-11eb-9610-f38be701dffe.png)

* The platform(s)/browser(s) where the issue is seen
Chrome
* A screenshot of http://webglreport.com/ (for graphics related issues) >> http://webglreport.com/ is down for the moment

### Steps to Reproduce

1. Editor launch ... for benchmark
2. Publish to canv.as-server
3. Publish to own server

**Comment by Maksims** [comment] 2020-12-14 22:10
Check your console, there are errors related to completely other things.

**Comment by yaustar** [comment] 2020-12-14 22:43
Looks like your code is looking to split the URL with '?' as the separator:
```
CommScrScript.prototype.gfg_Run = function() {
    location.href;
    var t = window.location.href.split("?")[1];
```
Except in the build link provided, there is no '?' so t is null.

**Comment by yaustar** [comment] 2020-12-14 22:44
Closed as it is project code that is at fault here, not the Editor.

**Closed** 2020-12-14 22:44 UTC

**Comment by FutureFireplace** [comment] 2020-12-15 06:21
ok, after three try/catch'es it works at published level as well, and can see that the issue is closed.
Without knowing all the editor and how it exports, I am still wondering - though - why the console works so differently post-export (?)

**Comment by FutureFireplace** [comment] 2020-12-15 06:22
... anyways I think I had a similar challenge a year ago - will try to work with the method of; 'using the published console better'

**Comment by yaustar** [comment] 2020-12-15 08:57
The issue is not the console, not the build process or export but the project code logic:

Here's the code in question:
```
CommScrScript.prototype.gfg_Run = function() {
    location.href;
    var t = window.location.href.split("?")[1];
    console.log(t);
    var i = t.toString().split("@");
    console.log(i[1]);
```

When you launch from the Editor, by default it gives you the following URL where there's a param `debug` in the path: https://launch.playcanvas.com/1004487?debug=true

```
var t = window.location.href.split("?")[1];
```

So the code above will split the string by the "?" so it gives you an array of `["https://launch.playcanvas.com/1004487", "debug=true"]` and `t` is given the value of "debug=true" as you giving it the 2nd element value

With a URL such as https://launch.playcanvas.com/1004487 or https://playcanv.as/e/b/SnHV73c7/ there isn't a "?".

The split will gives you an array of `["https://launch.playcanvas.com/1004487"]` so when you try to access the 2nd element of the array, `t` is given a value of null.

This is problematic when you do the following:
```
    var i = t.toString().split("@");
```
Doing `t.toString()` will crash the project as `t` is null.

This is the issue. The code assumes that there is always at least one parameter.

What it should be do is checking the length of the array. ie:
```
CommScrScript.prototype.gfg_Run = function() {
    location.href;
    var params = window.location.href.split("?")[1];
    if (params.length >= 2) {
        t = params[1]    
        console.log(t);
        var i = t.toString().split("@");
        console.log(i[1]);
```

**Comment by FutureFireplace** [comment] 2020-12-16 18:01
yes - agree ... and thanks for the details/explicit run through 
(by use of try/catch I might have done a rudimentary 'data validation' that worked afterwards ... after my initial troubles)
