### ISSUE TITLE
Unable to use a loading script

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/editor#1136] opened 2024-04-04 11:32 UTC
Add a default loading script from the project settings. Then build a project with disabled concatenation. The app throws when launched:

![image](https://github.com/playcanvas/editor/assets/5677782/89a532a2-2fa4-40c9-9eac-60ec14c102b8)

Repro: https://playcanvas.com/project/1205863/overview/loading-script-issue

**Comment by marklundin** [comment] 2024-04-08 05:50
Ok, this happens when the loading script is marked to preload, which obviously doesn't make sense in this scenario as it's bundled into __loading__.js. I'll check to see what changed

**Comment by marklundin** [comment] 2024-04-08 06:36
Closing as this seems to be a duplicate of https://github.com/playcanvas/editor/issues/613

**Closed by marklundin** 2024-04-08 06:36 UTC
