### ISSUE TITLE
iOS Download doesn't work

### ISSUE THREAD

**Issue by Nazar690** [playcanvas/editor#57] opened 2020-04-29 07:36 UTC
I have a problem with IOS Download. I can’t get build. It preparing a build all time and I have infinitely loading.  
![image](https://user-images.githubusercontent.com/17389638/80571392-39f44200-8a05-11ea-91c6-bf4abe8e9352.png)

**Comment by willeastcott** [comment] 2020-04-29 10:04
Thanks for reporting @Nazar690 - we are investigating. We'll report back as soon as this is fixed.

**Comment by mariogarranz** [comment] 2020-04-29 10:12
Just a little update, this issue seems not to affect iOS download only, but builds in general.

When I try to create regular HTML5 builds through the API I get a build job id, but that job stays as "running" forever.

https://forum.playcanvas.com/t/ios-download-doesnt-work/12899/10?u=mariogarranz

**Comment by willeastcott** [comment] 2020-04-29 10:41
OK, this should now be fixed so I'm closing this. But if problems persist, please re-open. Thanks!

**Comment by Nazar690** [comment] 2020-04-30 09:27
@willeastcott  I have this bug again.

**Comment by willeastcott** [comment] 2020-04-30 09:35
@slimbuck is investigating @Nazar690

**Comment by slimbuck** [comment] 2020-04-30 16:12
Hi @Nazar690 ,

Sorry for the download issues you're having. We are looking at our backend, but since the issue is transient, we're finding it hard to nail down.

We'll keep you posted as we make progress, but hopefully downloads don't fail too often for you till we can solve it.

Thanks!

**Comment by willeastcott** [comment] 2020-07-21 14:01
iOS has been removed from the platform so I'm closing this issue. To build a native app from a PlayCanvas app, either:

* Create an XCode project with a fullscreen WKWebView and add your app files.
* Use a solution like PhoneGap.

**Closed by willeastcott** 2020-07-21 14:01 UTC
Labels: bug
