### ISSUE TITLE
Editor always reports Missing UV1 on RenderComponents

### ISSUE THREAD

**Issue by eproasim** [playcanvas/editor#478] opened 2021-07-29 14:33 UTC
It is known that the editor is currently unable to unwrap UV1 for GLB models; however, even if an uploaded model has a UV1 channel, the editor will always report that it is missing when slecting a RenderComponent to be lightmapped. ModelComponents do not exhibit this behavior. When launching the scene, the RenderComponent will not respond to lightmapped lights, while the ModelComponents will.

Provide as much information as possible. Include (where applicable):

* URL to a simple, reproducible test case that illustrates the problem clearly:

https://playcanvas.com/editor/scene/1202294

### Steps to Reproduce

1. Open Project 
2. Verify that lightmapping is enabled on RenderComponent, ModelComponent, and Lights (While separate files, imported FBX are identical)
3. Launch Project

**Comment by willeastcott** [comment] 2021-07-29 14:53
Assigned this to you for now @mvaligursky - I know @slimbuck has some involvement in UV1 generation though so feel free to reassign as appropriate. 😄

**Comment by eproasim** [comment] 2021-08-09 13:17
Quick update. The editor still reports the UV1 is missing and sizes the lightmap at 1x1, but if you multiply the RenderComponents lightmap size by 5,000,000, it will for the map to be 1024x1024 to match the ModelComponent and light the models accordingly.

Not sure what to make of this behavior.

**Comment by mvaligursky** [comment] 2021-09-30 10:40
The issue is on the Editor side - it shows the missign uv1 error even though the mesh contains the uv1. If the mesh contains uv1 this warning can be ignored, as all still works.

The scaling is engine issue that I will have fixed: https://github.com/playcanvas/engine/issues/3528

**Comment by mvaligursky** [comment] 2021-09-30 10:42
related PR for reporting missing UV1 which does not seem to work well (monorepo/pull/391)
@slimbuck

**Comment by yaustar** [comment] 2022-02-08 15:15
I will settle for rewording the warning to 'may be missing'

**Comment by yaustar** [comment] 2022-03-02 15:17
released in 1.21.29

**Closed by yaustar** 2022-03-02 15:17 UTC
Labels: bug, area: asset import, blitz candidate
