### ISSUE TITLE
Asset selection by collaborative user color tag is offset.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#179] opened 2020-10-11 12:16 UTC
When collaborative user is selecting asset, it renders color coded box of that user (useful feature).
But if List view is used, it will offset the box to next line, making row higher.

Notice orange box is not after filename, but on next line.
![image](https://user-images.githubusercontent.com/636263/95678170-9e7e1480-0bd3-11eb-8867-d36f53d31b6c.png)

Fix: render color cube at the end of that name column.

### Solution:

Add style to `.pcui-asset-panel-users` when it is rendered as list:
```css
margin-top: 7px;
float: right;
flex-direction: row;
```

**Comment by vkalpias** [comment] 2020-11-11 11:43
Hi!

I'm not able to reproduce that can you check if this is still happening? And which browser / version / OS you're using?

Thanks

**Comment by willeastcott** [comment] 2020-11-11 12:42
Could this be related to browser tab scaling, @Maksims?

**Comment by Maksims** [comment] 2020-11-11 23:26
It has been changed since (improved), but still looks wrong (not centered vertically):
![image](https://user-images.githubusercontent.com/636263/98876037-12873300-2486-11eb-8d50-06077108d7ed.png)

**Comment by vkalpias** [comment] 2020-11-12 09:51
That was actually by design to accommodate up to 2 rows of indicators.. It's not great but open to ideas :)

**Comment by Maksims** [comment] 2020-11-12 13:27
Row is very wide to accommodate number of dots. Seeing large number of dots is less useful than seeing few specific ones. So having one row, and limit it to (8?) dots, I believe is a reasonable solution.

**Comment by willeastcott** [comment] 2020-11-12 16:58
Yeah, sounds reasonable to me.

**Comment by vkalpias** [comment] 2020-11-18 09:03
OK this will be fixed in next release.

**Closed** 2020-11-18 14:57 UTC
Labels: area: ui, bug
