### ISSUE TITLE
Expose 'Opacity Fades Specular' on StandardMaterial

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/editor#1007] opened 2023-03-30 07:49 UTC
It seems this is not enabled / exposed yet?

![image](https://user-images.githubusercontent.com/59932779/228766489-0572a0a8-39b4-4de7-bc1a-9ed3d99635ab.png)

This is what the users see:

![image](https://user-images.githubusercontent.com/59932779/228766730-db9373df-8e81-4fda-a5aa-7147fd004e79.png)

**Comment by yaustar** [comment] 2023-03-30 08:51
Do we want to expose it? We can do that quite easily if it's done and we want users to use it

**Comment by willeastcott** [comment] 2023-06-17 01:03
Duplicate of #191. Closing.

**Closed by willeastcott** 2023-06-17 01:03 UTC
