### ISSUE TITLE
solution needed for samsung tablet with s pen

### ISSUE THREAD

**Issue by g1i1U** [playcanvas/editor#921] opened 2022-11-08 18:30 UTC
### Steps to Reproduce

1. run on samsung tablet with s pen
2. can not do anything on canvas

**Comment by willeastcott** [comment] 2022-11-08 19:28
I have actually just opened a pull request which adds touch (and pen) support to the 3D view of the Editor. It uses pointer events to abstract user input. It's not quite done but hopefully I can merge it in the next week or two.

**Comment by willeastcott** [comment] 2024-11-10 11:44
This is a duplicate of https://github.com/playcanvas/editor/issues/128. Closing.

**Closed by willeastcott** 2024-11-10 11:44 UTC
Labels: area: viewport, feature request
