### ISSUE TITLE
Ability to filter by name in the Scene picker

### ISSUE THREAD

**Issue by Mintytorus** [playcanvas/editor#1193] opened 2024-09-04 10:38 UTC
Our project has a lot of scenes and the scene picker UI is getting unwieldy.

It would be incredibly useful to have a search/filter text box a la the version control branch list to allow us to find scenes quickly. It will also allow us to implement a scene naming convention that'll allow us to categorise and find scenes using keywords.

**Comment by mvaligursky** [comment] 2024-09-04 10:44
duplicate of https://github.com/playcanvas/editor/issues/461

**Closed by mvaligursky** 2024-09-04 10:44 UTC
