### ISSUE TITLE
console.log in Editor - freezes the Editor

### ISSUE THREAD

**Issue by Maksims** [playcanvas/editor#583] opened 2021-10-20 10:49 UTC
### Steps to Reproduce:

1. Open Editor
2. Open Dev Tools > Console
3. Execute `console.log(pc);`

### Issue:
It freezes the Editor
The issue seems to be related to sentry, it tries to sanitize provided log data but falls somewhere in an infinite cycle.

**Comment by yak32** [comment] 2022-09-28 21:23
the issue is fixed and merged, will be deployed with the next release of the editor

**Closed** 2022-09-28 21:23 UTC
Labels: bug
