### ISSUE TITLE
Issue with Entity Element Margin in Template

### ISSUE THREAD

**Issue by s-stafeev** [playcanvas/editor#1095] opened 2024-02-08 10:53 UTC
If entities in a Template on the scene have fractional parameters for their position, it’s impossible to apply Margin to the template. Consequently, this parameter is highlighted in turquoise and marked as Override. When the position only has integer values, this issue does not occur, and Margin is applied to the Template.

![image](https://github.com/playcanvas/editor/assets/47380574/25144031-cae7-4d4c-a5b3-72f29ff94519)

![image](https://github.com/playcanvas/editor/assets/47380574/98b25a1b-e573-42e0-ab36-b065e63a0707)

**Comment by yaustar** [comment] 2024-02-08 14:07
Duplicate of https://github.com/playcanvas/editor/issues/842

**Closed** 2024-02-08 14:08 UTC
