### ISSUE TITLE
Editor show object created time, but not edited

### ISSUE THREAD

**Issue by alamboley** [playcanvas/editor#549] opened 2021-09-14 15:49 UTC
Hey, it would be nice to know when an object has been updated compared to created time.

<img width="333" alt="Capture d’écran 2021-09-14 à 17 48 29" src="https://user-images.githubusercontent.com/687978/133290901-6096e534-8c25-4a33-ac93-449c26433c62.png">

**Comment by yaustar** [comment] 2021-09-14 15:50
Closed, duplicate of https://github.com/playcanvas/editor/issues/363

**Closed by yaustar** 2021-09-14 15:50 UTC
