### ISSUE TITLE
Disable warnings for ES6 scripts

### ISSUE THREAD

**Issue by yaustar** [playcanvas/editor#112] opened 2020-07-29 18:06 UTC
Remove the need for JShint in the code editor

**Comment by willeastcott** [comment] 2020-07-30 07:24
Perhaps as an intermediate step, we should make this an user preference that defaults to off.

**Comment by willeastcott** [comment] 2020-10-29 23:44
Probably a duplicate of #64 BTW.

**Comment by Maksims** [comment] 2021-01-14 12:11
I believe JSHint should be enabled by default. It is still recommended to use ES5 as it covers majority of platforms.
If developer issues ES6+ feature. Then we perhaps could identify it. And if settings of the project is not ES6+, then show small option in IDE bellow screen (non-obtrusive) for enabling ES6 or higher. And have this in project settings.
So everyone will be happy: ES5 by default. And ES6+ if enabled.

**Comment by yaustar** [comment] 2021-01-14 13:20
We should update jshint to latest on the backend as we don't have linting for es9 support

**Comment by willeastcott** [comment] 2021-01-14 13:43
@Maksims - I think we should enable Babel on the backend and default it to on. It seems crazy in 2021 to be coercing developer into sticking to ES5. And then, we don't need to worry about bothering developers about the language features they use in the Code Editor.

**Comment by Maksims** [comment] 2021-01-14 16:15
> @Maksims - I think we should enable Babel on the backend and default it to on. It seems crazy in 2021 to be coercing developers into sticking to ES5. And then, we don't need to worry about bothering developers about the language features they use in the Code Editor.

You are probably right. Its probably requires a bit more through into it: figuring out ES5+original compilation approach. That way it will use ES5 with ES5 engine for older platforms, and original with ES6 engine for modern platforms. Also a way to launch with ES5 for optional testing (like WebGL 1 option in Launcher). So nor developer nor user will have to think about it, while we deliver best of both worlds.

**Comment by willeastcott** [comment] 2021-04-11 08:39
I believe this has been done, so closing.

**Closed by willeastcott** 2021-04-11 08:39 UTC
Labels: area: code editor, duplicate, enhancement
