### ISSUE TITLE
Add cherry-picking to version control

### ISSUE THREAD

**Issue by ki11roy** [playcanvas/editor#534] opened 2021-09-07 15:40 UTC
It would be nice to have a cherry-picking feature, similar to git one, to merge changeset from "theirs" branch into "ours" (current) as a separate commit.
![image](https://user-images.githubusercontent.com/1812070/132373003-fea224b0-3abb-48d8-9190-b465f1929da9.png)

**Comment by yaustar** [comment] 2021-09-07 15:47
Closed as duplicate of https://github.com/playcanvas/editor/issues/492

**Closed by yaustar** 2021-09-07 15:47 UTC
