### ISSUE TITLE
Videos with no audio throw error

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/editor#886] opened 2022-09-20 15:41 UTC
If you play [this project](https://playcanvas.com/project/985013/), you will get the error

`Error loading audio url: simon-flying-masked.mp4: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data`

**Comment by yaustar** [comment] 2022-09-20 15:46
The issue is that the file is treated as an audio asset which is a longer standing bug here: https://github.com/playcanvas/editor/issues/266

Closing as a duplicate. 

Generally, you don't want to preload mp4 videos due to the size and they actually naturally stream being a video in the browser.

**Closed by yaustar** 2022-09-20 15:46 UTC
Labels: bug, area: assets
