### ISSUE TITLE
Having many items in an opened folder/scene hierarchy degrades performance

### ISSUE THREAD

**Issue by lucaheft** [playcanvas/editor#862] opened 2022-08-16 14:15 UTC
### Description
When opening a folder in the assets panel, which contains many items, performance of the editor degrades drastically. Same behaviour also applies for the scene hierarchy panel.

This is probably not a "bug" with the editor but has more to do with how pcui renders those elements.
I think a solution which is applied often in this case, is to not render the items which are not in view (hidden because of scroll bar).

### Steps to Reproduce
1. Create a folder with many items inside
2. Open the folder
3. Performance is bad

**Comment by yaustar** [comment] 2022-08-16 14:16
Closed as duplicate of https://github.com/playcanvas/editor/issues/746

**Closed by yaustar** 2022-08-16 14:16 UTC
